--DROP TABLE invoice IF EXISTS;

CREATE TABLE invoice (
  invoice_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
  name VARCHAR(30),
  email  VARCHAR(50),
  due_date DATE,
  description VARCHAR(50),
  amount DOUBLE 
);